### ISSUE TITLE
Minor conflicts

### ISSUE THREAD

**Issue by farakiko** [FNALLPC/machine-learning-hats#8]
1) In **2-plotting**: in the last cell (plotting with plt), there’s an issue that sometimes arises when you pre-specefy bins for plotting with plt in pandas due to unfortunate notations.. it gets resolved when you change plot.hist(bins) to plot.hist(bins=bins)

2) In **3.2-dense-bayesian-optimization**: i think in the function build_custom_model, the output layer should act on the “hidden” instead of the “inputs”.. you can also see that because all model summaries appear to be the same during hyper-parameter tuning

3) In the same notebook, in the last cell, no errors if you change history.history['acc'] to history.history['accuracy'], and the same for validation in next line

4) Lastly, **4-preprocessing** is written in python2, so it needs syntax changes to work with the kernel

**Comment by aperloff** [comment]
Most of this should be fixed by PR#9. I didn't fully test *4-preprocessing*, but it's and optional notebook for now and can be updated in the future. Feel free to reopen the issue if you find that some items still aren't fixed.
